package rentcar;
import java.time.LocalDate;

public class DialogKembalikanMobil extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogKembalikanMobil.class.getName());
    private FleetManager manager;

    public void setFleetManager(FleetManager m) {
        this.manager = m;
        for (Pemesanan p : m.getPemesananAktif()) {
            jComboBox1.addItem(p.getIdPemesanan() + " - " + p.getMobilDisewa().getMerk() + p.getMobilDisewa().getTipe());
        }
    }

    /**
     * Creates new form DialogKembalikanMobil
     */
    public DialogKembalikanMobil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mobil yang Dikembalikan:");

        jLabel2.setText("Tanggal Kembali:");

        jButton1.setText("OK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cancel");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel3.setText("Diskon                            Rp:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 191, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = jComboBox1.getSelectedIndex();
        if(index == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih Kendaraan yang ingin dikembalikan", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String tglStr = jTextField1.getText().trim();
        if (tglStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Tanggal kembali harus diisi!", "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String diskonStr = jTextField2.getText().trim();
        double diskon = 0.0;
        
   try {
        if (!diskonStr.isEmpty()) {
                diskon = Double.parseDouble(diskonStr);
                if (diskon < 0) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Diskon tidak boleh negatif!", "Peringatan",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
       
        Pemesanan pesanan = manager.getPemesananAktif().get(index);
        LocalDate tglAktual = LocalDate.parse(jTextField1.getText());
        
        // Hitung biaya awal
        long durasi = pesanan.hitungDurasiSewa();
        double tarif = pesanan.getMobilDisewa().getTarifPerHari();
        double biayaAwal = durasi * tarif;

        // Hitung denda dan total
        Pembayaran bayar = new Pembayaran(diskon, biayaAwal);
        bayar.hitungDenda(pesanan, tglAktual);
        bayar.hitungBiayaAkhir();
        
        //struk pengembalian
        String struk = "=================STRUK PENGEMBALIAN=================\n"
        + "ID Pesanan\t: " + pesanan.getIdPemesanan() + "\n"
        + "Nama Penyewa\t: " + pesanan.getPenyewa().getNamaPelanggan() + "\n"
        + "Kendaraan\t: " + pesanan.getMobilDisewa().getMerk() + " " + pesanan.getMobilDisewa().getTipe() + "\n"
        + "--------------------------------------------------------------\n"
        + "Tanggal Ambil\t: " + pesanan.getTanggalAmbil() + "\n"
        + "Batas Kembali\t: " + pesanan.getTanggalKembali() + "\n"
        + "Dikembalikan\t: " + tglAktual + "\n"
        + "Durasi Sewa\t: " + durasi + " Hari\n"
        + "Tarif per Hari\t: Rp" + String.format("%,.0f", tarif) + "\n"
        + "--------------------------------------------------------------\n"
        + "Biaya Sewa\t: Rp" + String.format("%,.0f", biayaAwal) + "\n"
        + "Denda Keterlambatan\t: Rp" + String.format("%,.0f", bayar.getDenda()) + "\n"
        + "Diskon\t\t: Rp" + String.format("%,.0f", bayar.getDiskon()) + "\n"
        + "--------------------------------------------------------------\n"
        + "TOTAL BAYAR\t: Rp" +String.format("%,.0f", bayar.getBiayaAkhir()) + "\n"
        + "====================================";
        
        javax.swing.JOptionPane.showMessageDialog(this, struk, "Struk Pembayaran Rental", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    // Update status
        pesanan.getMobilDisewa().setStatusKendaraan("Tersedia");
        pesanan.setStatusSelesai(true);

        this.dispose();
        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Format tanggal salah! Gunakan yyyy-MM-dd (contoh: 2026-06-17)",
                "Format Salah", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogKembalikanMobil dialog = new DialogKembalikanMobil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
